# fly.toml app configuration file generated for zenon-backend on 2023-10-19T13:47:12+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zenon-backend"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
