# fly.toml app configuration file generated for zenon-etl on 2023-10-25T14:38:20+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zenon-etl"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
